### ISSUE TITLE
h2 id is consistently removed

### ISSUE THREAD

**Issue by tommyvn** [rehypejs/rehype-sanitize#11]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.0.0

### Steps to reproduce

no build or bundle tools, only the specific npms required to run this bit of code.

```
import {unified} from 'unified'
import rehypeParse from 'rehype-parse'
import rehypeSlug from 'rehype-slug'
import rehypeSanitize from 'rehype-sanitize'
import rehypeStringify from 'rehype-stringify'

  unified()
    .use(rehypeParse)
    .use(rehypeSlug)
    .use(rehypeSanitize)
    .use(rehypeStringify)
    .processSync('<h1>foo</h1><h2>bar</h2><h3>baz</h3>')
```

### Expected behavior

h2 to have an id:

```
<h1 id="user-content-foo">foo</h1>
<h2 id="user-content-bar">bar</h2>
<h3 id="user-content-baz">baz</h3>

```

### Actual behavior

h2 does not have an id:

```
<h1 id="user-content-foo">foo</h1>
<h2>bar</h2>
<h3 id="user-content-baz">baz</h3>
```

### Runtime

Node v16

### Package manager

npm 8

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Looks a lot like https://github.com/syntax-tree/hast-util-sanitize/issues/27 :)

**Comment by tommyvn** [comment]
lmao that's it.
Am I reading that correctly, that h2 is restricted to a specific id because github uses it in this way? that's wild.
anyway, this answers my question, sounds like it's a feature (for GH at least) not a bug, so i'm closing this one, I'll follow the advice on that issue to use my own schema.
thanks for the link :)

**Comment by wooorm** [comment]
Btw, if you want to help that issue along, I’m very open to a PR!
