### ISSUE TITLE
Schema ancestors are not respected

### ISSUE THREAD

**Issue by emilnordh** [rehypejs/rehype-sanitize#8]
### Subject of the issue

A schemas `ancestors` property is not respected.

### Your environment

*   **OS**: macOS 10.15.2
*   **Packages**: hast-util-sanitize@3.0.1, rehype-sanitize@4.0.0
*   **Env**: Node@12.14.1 npm@6.13.4

### Steps to reproduce

Simple schema:
```json
{
  "ancestors": {
    "li": ["ul"]
  },
  "tagNames": [
    "div",
    "ul",
    "li"
  ]
}
```

HTML:
```html
<div>
  <li>List Item</li>
</div>
```

### Expected behavior

Expecting the resulting tree to exclude the `li` tag:
```
root[1]
│ data: {"quirksMode":true}
└─0 element<div>[3]
    │ properties: {}
    ├─0 text "\n  "
    ├─1 text "List Item"
    └─2 text "\n"
```

### Actual behavior

The `li` tag is still included:
```
root[1]
│ data: {"quirksMode":true}
└─0 element<div>[3]
    │ properties: {}
    ├─0 text "\n  "
    ├─1 element<li>[1]
    │   │ properties: {}
    │   └─0 text "List Item"
    └─2 text "\n"
```

I investigated a bit and it seems like this bug has appeared because of this: https://github.com/syntax-tree/hast-util-sanitize/commit/19631bb6dc80ca9a22d70350fff80bf8f6585225#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R252. I can create a PR for it if you want.

**Comment by wooorm** [comment]
I pushed a test that checks that your actual behavior works: https://github.com/syntax-tree/hast-util-sanitize/commit/3068a468b6052354c7136108201f98483c546f51.
Maybe it has to do with the rest of your code?

**Comment by emilnordh** [comment]
It seems to work if using `hast-util-sanitize` directly. I think the issue arises when using it with `rehype` because of the `root` object?

**Comment by wooorm** [comment]
I doubt that rehype is doing anything weird: https://github.com/rehypejs/rehype-sanitize/blob/a6ddc5eee07b7e2bdbeed1e9d9e9f045989bd9ec/index.js

Can you provide a reproduction?

**Comment by wooorm** [comment]
You’re right, it’s the `root` node!

**Comment by emilnordh** [comment]
Reproduction code:
```javascript
const rehype = require('rehype');
const sanitize = require('rehype-sanitize');

const schema = {
  "ancestors": {
    "li": ["ul"]
  },
  "tagNames": [
    "div",
    "ul",
    "li"
  ]
};

const html = `<div>
  <li>List Item</li>
</div>`;

(async function run() {
  const vfile = await rehype().use(sanitize, schema).process(html);
})();
```

**Comment by wooorm** [comment]
thanks, released a fix!
